### ISSUE TITLE
duplicated output

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/PaymentService#51]
```
09:14:04.548 [bitcoinj user thread] INFO org.bitcoinj.wallet.Wallet - Completing send tx with 30 outputs totalling 0.03 BTC and a fee of 0.001 BTC/kB
09:14:04.548 [bitcoinj user thread] INFO org.bitcoinj.wallet.Wallet -   with 0.030746 BTC change
09:14:04.551 [bitcoinj user thread] INFO org.bitcoinj.wallet.Wallet -   completed:   ffdf52eac61001dcedc4e275d921ec82a3dd9b382a65bac67bf1ea50d248fcef
     in   PUSHDATA(72)[3045022100a556ea469c6c578ef81358e78e23eaa1ef8b0eb30a561828c32deaec64ec3cea0220713c2365e2451ca380d8333a59b4d6bc3c821e27437e4a1ad9a912183cb4964c01] PUSHDATA(33)[03ba3a981c18fd2ffaa4904e1b258f0bcc7119b70262cf60b4947f39b02e1f7257]
          outpoint:295566837da2f51808d0f89695ddac8fa408f383c6c7d923241f0201f8bcc880:0 hash160:1f1b0f5f93a232558ee440f4907c9b1c878d7b48
     in   PUSHDATA(71)[304402200360135a626cc8c6ec8aa509ce4483bc9c9d4d966bf5b0017d20374233f011bb022017131c4d1b21ce78ef037a50b219df7fcda465921640dac257dd9929a1a33fa801] PUSHDATA(33)[03ba3a981c18fd2ffaa4904e1b258f0bcc7119b70262cf60b4947f39b02e1f7257] 0.031 BTC
          outpoint:295566837da2f51808d0f89695ddac8fa408f383c6c7d923241f0201f8bcc880:0 hash160:1f1b0f5f93a232558ee440f4907c9b1c878d7b48
     out  DUP HASH160 PUSHDATA(20)[d17e625cfe83fca5674e27d19b642f5d85db78fa] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[da040e437dc756ba20811a03e46e8f3ccbc9f514] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[eb85754550646e76bb3db4a7c95e62dad67f9121] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[cb40bee423767ba6bf23a337d02b8f54051168ca] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d03958a62d5a88834ebdcf0a9248ee9c296f43a9] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e761ef9b3295544327f85748c840f4c1319db479] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[cc27762c2e3de0262c471fdcdad1f01799e913a9] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d5682e99fb1d2fa8683459d8a9917df9a8807756] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[dcfcd900738ddf0382e23bd5fdffec1cc9a71c02] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d807cbaa1ed065808054d373890ee1c60642bdde] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d865396bd8891d677bb50768dbc30e86b90e041b] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e494e6f67413f19dea5470cedd5e4fd8867c1d04] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[6d25bbbdff4f619e4c471e768eeb997db8ff38c1] EQUALVERIFY CHECKSIG 0.030746 BTC
     out  DUP HASH160 PUSHDATA(20)[cfd17e6195eb056e6270b80bc026bdea75b99d07] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[de96b36e8a8d2d1bce65b727869aa270c8a77984] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[eb37e21981851aad0ed5c422718e1d2fa426276d] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d4d3474e91050564a14e5712663200df8fc82f62] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e0e60b944d3a2406d592584ce77594588c4397a9] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d477707f56cf624d450173ec848e1474b8d8f006] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e0008f4fa94842afff2e6295772ce88d31685bce] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e5606fd57f7c1a6bbda822c0a32e7c34bbca0f56] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d3b85c938519de12537fed62dc2478b25d55b000] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d7eb17f9441201af34a12fb52696520686194dd3] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[cc50f707fe36f3d64c12f2d2f31078b0ac00e192] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d996d8f88a1e6b23d34c1d1767dc9817212578e8] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[df85d8d516c3073a9799ee202781a859bc28606f] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[cfe86d3970b539493879e736176bf00741556021] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[df64a1c672f3f702ee61bf3c680ae6e261ce17dc] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[d45a6ad98ad4b834b6aebf5966cf0ae8e1433d26] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[ca4b7893cd42e12d581062dc2add27d43aafa3e2] EQUALVERIFY CHECKSIG 0.001 BTC
     out  DUP HASH160 PUSHDATA(20)[e6236ccde1cb33d18957f32b28c631ad1aabe4df] EQUALVERIFY CHECKSIG 0.001 BTC
     prps USER_PAYMENT

09:14:04.554 [bitcoinj user thread] WARN org.bitcoinj.utils.Threading$UserThread - Exception in user thread
org.bitcoinj.core.VerificationException$DuplicatedOutPoint: Duplicated outpoint
	at org.bitcoinj.core.Transaction.verify(Transaction.java:1262)
	at org.bitcoinj.wallet.Wallet.maybeCommitTx(Wallet.java:2402)
	at iuno.tdm.paymentservice.Bitcoin.onWalletChanged(Bitcoin.java:413)
	at org.bitcoinj.wallet.Wallet$4.run(Wallet.java:2748)
	at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107)
```

**Comment by bockha** [comment]
The duplicated outpoint is added as input by ```Wallet.complete()```.
